name: Deployment aws

on: 
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build java
        run: mvn clean install -DskipTests

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        
      - name: Build docker image
        run: docker build -t uesleicristiano/my-school-transportation-api  .

      - name: push image docker
        run: docker push uesleicristiano/my-school-transportation-api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull uesleicristiano/my-school-transportation-api:latest
      - name: Remove docker container
        run: docker rm -f my-school-transportation-api
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL=${{secrets.DATABASE_URL}} -e JWT_SECRET=${{secrets.JWT_SECRET}} --name my-school-transportation-api uesleicristiano/my-school-transportation-api

